### PR TITLE
Bug flip vs rotate

### PR DESCRIPTION
**Pull request by VildeStabell**
I also removed the error on round end of objects continuing to spawn

### CODE REVIEW

**Comment by sigtheidiot** [comment]
The code looks good, but I'm still getting the MissingReferenceException error

**Comment by VildeStabell** [comment]
> The code looks good, but I'm still getting the MissingReferenceException error

What does the error say? I'm not getting it anymore, but it might be how we test. The only way I can see it happening (might be missing something) is if the board gets deleted immediately after the check but before SpawnNewObject is finished, which seems like an edge case.

**Comment by sigtheidiot** [comment]
I got this error, but maybe thats from stopping the game?

> Should not be capturing when there is a hotcontrol
> UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

**Comment by VildeStabell** [comment]
> 

Står det hvilken fil det er fra? Tror ikke jeg driver med noe sånt i min kode...

**Comment by sigtheidiot** [comment]
> Does it say which file it is from? I don't think I use any GUI in my code...

It didn't. But after some googling it looks like its an issue several people have had, with no clear answer of what its from. 

I also managed to replicate the MissingReferenceException, so I think you're right by it being because another object was being created as the game stopped. Do you want to try and fix it, or should I approve and merge?

**Comment by VildeStabell** [comment]
Now I also got the weird error. It happened when I manually stopped the game, so I don't think it matters

**Review by sigtheidiot — APPROVED** [review]

**Pull request merged**
